global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'healthpay-command-service'
    static_configs:
      - targets: ['command-service:3000']
    metrics_path: '/metrics'
