global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redpanda'
    static_configs:
      - targets: ['healthpay-redpanda:9644']

  - job_name: 'postgres'
    static_configs:
      - targets: ['healthpay-postgres:5432']

  - job_name: 'scylla'
    static_configs:
      - targets: ['healthpay-scylla:9180']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['healthpay-clickhouse:8888']

  - job_name: 'redis'
    static_configs:
      - targets: ['healthpay-redis:6379']
